#!/bin/bash
set -ex

# Since EC2 manages /mnt directory, the only
# meaningful time to change the permissions on the dir
# is when we have the instance up and running.
sudo chgrp -R deploy /mnt
sudo chmod -R g+w /mnt

dir="/home/deploy"
cmd="bin/deploy {{RELEASE_URL}}"
echo "at=start-deploy cmd=\"$cmd\" pwd=`pwd` user=`whoami`" | logger -t deploy
su deploy -c "cd $dir; $cmd | logger -t deploy"
